version: '3.7'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    env_file:
#      - .env
#    volumes:
#      - ./:/code
#    ports:
#      - "${APP_PORT}:5001"


  mysql_01:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '${MYSQL_FORWARD_PORT}:3306'

  redis_01:
    image: "redis:alpine"
    env_file:
      - .env
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    volumes:
      - ./volumes/redis:/var/lib/redis
    ports:
      - '${REDIS_FORWARD_PORT}:6379'

  elasticsearch_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch_01
    env_file:
      - .env
    environment:
      - cluster.name=ecommerce-server
      - transport.host=localhost
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.port=9200
    volumes:
      - ./volumes/es:/var/lib/es
    ports:
      - '${ES_FORWARD_PORT}:9200'

  kibana_01:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana_01
    env_file:
      - .env
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch_01:9200/
    ports:
      - '${KIBANA_FORWARD_PORT}:5601'

