"""empty message

Revision ID: 27883baf882b
Revises: 1c5a53e8315c
Create Date: 2020-06-29 16:03:11.528535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27883baf882b'
down_revision = '1c5a53e8315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('promotion_stock', sa.Integer(), nullable=True),
    sa.Column('promotion_price', sa.Float(), nullable=True),
    sa.Column('promotion_end_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('flash_sale_stock', sa.Integer(), nullable=True),
    sa.Column('flash_sale_price', sa.Float(), nullable=True),
    sa.Column('flash_sale_end_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.drop_table('stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('sku', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promotion_stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flash_sale_stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('sku'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('product')
    # ### end Alembic commands ###
