"""empty message

Revision ID: 3525f293eaeb
Revises: 5801eae4e487
Create Date: 2020-06-20 16:07:09.998206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3525f293eaeb'
down_revision = '5801eae4e487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('register', sa.Column('gender', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'register', ['gender'])
    op.create_unique_constraint(None, 'register', ['address'])
    op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['gender'])
    op.create_unique_constraint(None, 'user', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'address')
    op.drop_constraint(None, 'register', type_='unique')
    op.drop_constraint(None, 'register', type_='unique')
    op.drop_column('register', 'gender')
    op.drop_column('register', 'address')
    # ### end Alembic commands ###
