"""empty message

Revision ID: 3967d29544af
Revises: 129b1b66d2af
Create Date: 2020-06-28 14:09:36.149361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3967d29544af'
down_revision = '129b1b66d2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('promotion_stock', sa.Integer(), nullable=True),
    sa.Column('flash_sale_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
